Removed Modified Files By TayMcKenzieNZ
alberttheprince/CayoTwoIslands-YanktonCompatible pull request #1
Opened 2024-03-28 08:54 UTC by TayMcKenzieNZ

This pull request keeps the script from doing as it is intended to do and still works with North Yankton, however removes 3 years of Tay's work. I have been nice enough to provide you modified files which open the mansion gates for access, deleted and removed the underwater gate, removed the collisions at the beach party DJ booth, as well as around the island that Rockstar added, to stop boats from docking and the player being able to climb onto land.

I have also credit __**ALL**__ people involved in this project, respectfully!

Please take this as a lesson that you should ideally credit the original creator, or remove their content when asked.

2024-03-28 09:35 UTC, alberttheprince requested changes
When creating PRs, please make small, targeted PRs. The changes are too large to realistically check differences in a timely manner.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +Thank you to [TayMcKenzieNZ](https://github.com/taymckenzienz) for bringing Cayo Perico to FiveM.
This is unnecessary, as there is a link to the original repo in the main intro of the post.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +Thank you to [AvaN0x](https://github.com/AvaN0x) for fixing the minimap so Cayo Perico appears in the pause menu when pressing ESC on the keyboard.
This is a proper credit, as Avan0x does not appear in the credits, please follow this format.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +Just copy and paste the one provided, or the Cayo Perico Shops collision file **(h4_islandairstrip_12)** into the ybn folder.
Please do not delete flavour text/commentary by the original creator.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
Please do not delete features list, this is important for knowing what features and general GTA props were added to the map. Additionally the flavor text was part of the original repo.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> -
Please do not remove info on static emitters, something that is important to the functionality of this resource.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +> can't figure it out, open an issue on their resource.
Please use proper grammar/English. Please use appropriate pronouns.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +-  [Gamebuild 2189 or higher](https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build)
Please do not change links to publicaly available threads.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +CayoTwoIslands was a passion project of Tay's that began in December of 2020 to self teach himself Codewalker. I have modified it to work with North Yankton after discussing with TayMcKenzieNZ, who h
Please do not add superfluous statements, this is intended to preserve the resource as published by Tay Mackenzie and contributors.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +Designed for RP and exploration in mind.
Please do not remove links, as this potentially scrubs important archival information for FiveM documentation/history.

2024-03-28 09:35 UTC, alberttheprince commented on readme.md
> +I have removed some things I felt were unnecessary (personal opinion stylistically) and will make additional changes so things like ped traffic don't interfere with North Yankton's traffic and vice v
Please do not edit this portion, as it is my statement/preamble to the rest of the readme in light of Tay Mackenzie's original readme.

2024-03-28 11:59 UTC, TayMcKenzieNZ commented
I don't think you understand. This was MY resource. Since you're too lazy to remove my files, I did it for you. The scritp to load cayo perico and los santos side by side, works. THAT was your intentions. AvaN0x did in fact help me with this resource; I should know as I did the resource in the first place!

2024-03-28 12:00 UTC, TayMcKenzieNZ commented on readme.md
> +Designed for RP and exploration in mind.
link is dead. isn't needed anymore.

2024-03-28 12:01 UTC, TayMcKenzieNZ commented on readme.md
> +CayoTwoIslands was a passion project of Tay's that began in December of 2020 to self teach himself Codewalker. I have modified it to work with North Yankton after discussing with TayMcKenzieNZ, who h
excuse me?? you are seriously starting to piss me off. I created this resource, you haven't done shit but piss me off.

2024-03-28 12:01 UTC, TayMcKenzieNZ commented on readme.md
> +Thank you to [TayMcKenzieNZ](https://github.com/taymckenzienz) for bringing Cayo Perico to FiveM.
In case you didn't realise, the link doesn't work.

2024-03-28 12:02 UTC, TayMcKenzieNZ commented on readme.md
> +Thank you to [AvaN0x](https://github.com/AvaN0x) for fixing the minimap so Cayo Perico appears in the pause menu when pressing ESC on the keyboard.
If you read the original commits you would see that AvaN0x helped me fixed the minimap of cayo perico appearing 🙄. Credit the correct people, dude.

2024-03-28 12:02 UTC, TayMcKenzieNZ commented on readme.md
> +Just copy and paste the one provided, or the Cayo Perico Shops collision file **(h4_islandairstrip_12)** into the ybn folder.
I am the original creator!

2024-03-28 12:03 UTC, TayMcKenzieNZ commented on readme.md
These are featured I, Tay McKenzie worked on. You did not do ANTYTHING. REMOVE MY FILES!!

2024-03-28 12:04 UTC, TayMcKenzieNZ commented on readme.md
> -
No they aren't. Learn to code properly, i did this work, not you.

2024-03-28 12:04 UTC, TayMcKenzieNZ commented on readme.md
> +> can't figure it out, open an issue on their resource.
Please stfu and don't tell me what to do with my resource.

2024-03-28 12:04 UTC, TayMcKenzieNZ commented on readme.md
> +-  [Gamebuild 2189 or higher](https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build)
bla bla bla

2024-03-28 12:08 UTC, TayMcKenzieNZ commented
You clearly have no idea what cayo perico looks like originally. i spent 3 years on this map, and you have the audacity to tell me "pls dont reemove the feature list". excuse me? i created that list. you dont do anything but take credit and claim you're "preserving shit"

2024-03-28 17:13 UTC, alberttheprince commented
Due to the nature of your responses, I will unfortunately have to reject your pr at this time. Please only submit serious prs intended to improve functionality of this resource.

2024-03-28 17:13 UTC, closed without merging

2024-03-28 23:01 UTC, TayMcKenzieNZ commented
You're a joke. Remove my fucking files.

2024-03-31 13:43 UTC, Mandalorian531 commented
Alberttheprince You're a fraud leave the job to TayMcKenzieNZ, he brought so much to Cayo Perico, unlike you, you're a clown!

2024-03-31 20:17 UTC, TayMcKenzieNZ commented
> Alberttheprince You're a fraud leave the job to TayMcKenzieNZ, he brought so much to Cayo Perico, unlike you, you're a clown!


Obviously, I don't own code, and I have no problem with people modifying the code so that Los Santos, Cayo Perico and North Yankton work simultaneously, however in the PR, I simply removed the feature list and my modified files, of which I spent 3+ years on.

He claims he's "preserving the integrity of the resources" however why now? Why suddenly after I've been banned from this shitty toxic community, does our prince suddenly care and why is TheIndra backing it? 🤨🤔 

Very suspicious. I don't believe any preservation is being done here, especially when credits lead to nowhere and don't credit the proper people, and this guy doesn't know codewalker or Lua id his life depended on it.

Happy April Fools, you're a joke.

2024-03-31 21:42 UTC, Mandalorian531 commented
I also don't understand why he wakes up now for no reason. But what I do know is that his behavior is disgusting. I hope that Karma will take care of him.

2024-03-31 21:48 UTC, TayMcKenzieNZ commented
Why even bother 'preserving' resources if you're not going to update them?
Lol I'm going to update RPEmotes and CayoTwoIslands but unfortunately due
to people like this, I have to put it behind a paywall, so if this soo
called Prince wants these updates, he can pay me for it or he can learn to
modify and release his _*own*_ work, without piggy backing off of other
people 🤡

On Mon, 1 Apr 2024, 10:43 am Mandalorian531, ***@***.***>
wrote:

> I also don't understand why he wakes up now for no reason. But what I do
> know is that his behavior is disgusting. I hope that Karma will take care
> of him.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alberttheprince/CayoTwoIslands-YanktonCompatible/pull/1#issuecomment-2028912176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL3YMN7ZOWPELZGL5PJRIKTY3B7PFAVCNFSM6AAAAABFML7DYOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRYHEYTEMJXGY>
> .
> You are receiving this because you commented.Message ID:
> <alberttheprince/CayoTwoIslands-YanktonCompatible/pull/1/c2028912176@
> github.com>
>

2024-03-31 21:52 UTC, Mandalorian531 commented
This man is a really bad one, whether he moves his a*s or goes back to sleep with his toxic mentality.

2024-03-31 21:54 UTC, TayMcKenzieNZ commented
I see him in the forums policing it and telling people they have to include direct downloads and that X already exists why are you uploading Y, or that something is stolen or leaked; very ironic coming from someone who has expertise in thievery and leaking 🤡

2024-03-31 21:54 UTC, BrazyDevelopment commented
Oh dear

2024-03-31 22:02 UTC, TayMcKenzieNZ commented
![8l4axq](https://github.com/alberttheprince/CayoTwoIslands-YanktonCompatible/assets/49776183/8a3272f8-b4ad-487c-acb5-81c411aa7d82)

Thanks for letting us know. We agree there is an issue and we're looking into it.

2024-03-31 22:20 UTC, alberttheprince commented
> > Alberttheprince You're a fraud leave the job to TayMcKenzieNZ, he brought so much to Cayo Perico, unlike you, you're a clown!
> 
> Obviously, I don't own code, and I have no problem with people modifying the code so that Los Santos, Cayo Perico and North Yankton work simultaneously, however in the PR, I simply removed the feature list and my modified files, of which I spent 3+ years on.
> 
> He claims he's "preserving the integrity of the resources" however why now? Why suddenly after I've been banned from this shitty toxic community, does our prince suddenly care and why is TheIndra backing it? 🤨🤔
> 
> Very suspicious. I don't believe any preservation is being done here, especially when credits lead to nowhere and don't credit the proper people, and this guy doesn't know codewalker or Lua id his life depended on it.
> 
> Happy April Fools, you're a joke.

Happy Apirl Fools day! Although it's March 31st here.

Unfortunately, due to the lack of professionalism, you have displayed here in your replies and insinuations that I should "go back to sleep," I'm going to have to lock this conversation. 

While I appreciate the contributions you've made to this Open source project licensed under GPL 3.0, it seems you have generally lost perspective in this case. 

I hope you can take this as a sign that you should reevaluate your goals, and maybe seek the help and guidance needed to realign yourself with healthy, realistic mindsets on and offline.